fix(chromatic.yml): remove debug flag and add validation for Storybook folder existence

diff --git a/.github/workflows/chromatic.yml b/.github/workflows/chromatic.yml
--- a/.github/workflows/chromatic.yml
+++ b/.github/workflows/chromatic.yml
@@ -71,16 +71,28 @@ jobs:
         if: ${{ steps.affected.outputs['@apps/home-storybook'] == 'true' }}
 
       - name: Build Storybook - Packages
-        run: pnpm turbo run build-storybook --filter=@apps/packages-storybook -- --debug
+        run: pnpm turbo run build-storybook --filter=@apps/packages-storybook
         # Must be 'true' not true.
         if: ${{ steps.affected.outputs['@apps/packages-storybook'] == 'true' }}
+
+      - name: Validate Storybook folder exists
+        run: |
+            set -euo pipefail
+            DIR="apps/home/storybook/storybook-static"
+            if [ ! -d "$DIR" ]; then
+            echo "::error::Directory not found: $DIR"
+            echo "Current working dir: $(pwd)"
+            ls -la
+            exit 1
+            fi
+            echo "✅ Found directory: $DIR"
 
       - name: Chromatic - Home
         uses: chromaui/action@latest
         with:
             projectToken: ${{ secrets.HOME_CHROMATIC_PROJECT_TOKEN }}
             workingDir: apps/home/storybook
-            storybookBuildDir: home/runner/work/sg-next-architecture/sg-next-architecture/apps/home/storybook/storybook-static
+            storybookBuildDir: apps/home/storybook/storybook-static
             onlyChanged: true
             exitOnceUploaded: true
             # autoAcceptChanges: 'main'
